install.packages('openxlsx')
install.packages('mosaic')
install.packages('vcd')
install.packages('dplyr')
getwd()
setwd("/Users/minhui/Documents/SDA1/Lab3")
SmartPhones = load("SmartPhones.RData")
str(SmartPhones)
head(SmartPhones)
